# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

services:
  app:
    image: zsh-aws-app-test
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
